#define ID_RESOURCE      1

#define IDM_SELECT       2

#define IDM_ABOUT        10
#define IDM_ENTRIES      11

#define IDD_ABOUT        21
#define IDD_DATA         22
#define IDD_KEY          23
#define IDD_KEYDISPLAY   24

#define IDD_ENTRYFLDJAN  31
#define IDD_ENTRYFLDFEB  32
#define IDD_ENTRYFLDMAR  33
#define IDD_ENTRYFLDAPR  34
#define IDD_ENTRYFLDMAY  35
#define IDD_ENTRYFLDJUN  36
#define IDD_ENTRYFLDJUL  37
#define IDD_ENTRYFLDAUG  38
#define IDD_ENTRYFLDSEP  39
#define IDD_ENTRYFLDOCT  40
#define IDD_ENTRYFLDNOV  41
#define IDD_ENTRYFLDDEC  42

#define IDD_ENTRYFLDKEY  50
